export const songsArray = [
  {
    artist: "Omah Lay",
    songUrl: "./music/Omah_Lay_-_Come_Closer.mp3",
    title: "Come Closer",
    id: crypto.randomUUID(),
    duration: 2.35,
  },
  {
    artist: "Omah Lay",
    songUrl: "./music/Omah_Lay_-_I_m_A_Mess.mp3",
    title: "I'm A Mess",
    id: crypto.randomUUID(),
    duration: 2.33,
  },
  {
    artist: "Omah Lay",
    songUrl: "./music/Omah_Lay_-_Purple_Song.mp3",
    title: "Purple Song",
    id: crypto.randomUUID(),
    duration: 2.25,
  },
  {
    artist: "Ilona",
    songUrl: "./music/Llona-Ft-Wizard-Chan-Commander-(TrendyBeatz.com).mp3",
    title: "Commander",
    id: crypto.randomUUID(),
    duration: 2.47,
  },
  {
    artist: "Ilona",
    songUrl: "./music/Llona_Ft_FAVE_-_Cold_War.mp3",
    title: "Cold War",
    id: crypto.randomUUID(),
    duration: 3.15,
  },
  {
    artist: "Ilona",
    songUrl: "./music/Llona_Ft_Bella_Shmurda_-_HBP_Remix.mp3",
    title: "HBP Remix",
    id: crypto.randomUUID(),
    duration: 2.56,
  },
  {
    artist: "Vasa",
    songUrl: "./music/Vasa_-_BETTER_DAYS_Tunesloaded.com.mp3",
    title: "Better Days",
    id: crypto.randomUUID(),
    duration: 2.31,
  },
  {
    artist: "Vasa",
    songUrl: "./music/Vasa_-_Bolanle_CeeNaija.com_.mp3",
    title: "Bolanle",
    id: crypto.randomUUID(),
    duration: 2.5,
  },
  {
    artist: "Vicoka",
    songUrl: "./music/Vicoka_-_Port_Harcourt.mp3",
    title: "Port Harcourt",
    id: crypto.randomUUID(),
    duration: 2.5,
  },
];
